import sqlite3
conn = sqlite3.connect("Diseases.db")
c = conn.cursor()

diseases_data = [
    ('EB001','Early Blight','Early blight, caused by Alternaria solani fungus, primarily affects nitrogen levels in potato tubers. High humidity or prolonged leaf wetness promotes its spread. Soil pH below 5.0 or above 7.0 impacts the overall health and vigor of the potato plant potato plants, increasing susceptibility to early blight.','Choose late-season, blight-resistant varieties;Time irrigation to minimize leaf wetness during cloudy weaather;Prevent N & P deficiencies;Scout for infection after 12-inch plant height;Focus on field edges near prior potato crops;Rotate foliar fungicides;Kill vines 2-3 weeks before harvest;Store tubers in optimal conditions for wound healing for 2-3 weeks after harvest;Implement a 3-4-year crop rotation.','Potato','Commercial solutions: Shop Foliar Fungicide: https://www.amazon.in/Bayer-Folicur-Systemic-Fungicide-Litre/dp/B088GN3FS5?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A1ZSKCLHK592D5 ; Home remedies: Promptly remove and destroy affected leaves;Create an alkaline spray with 1 tbsp baking soda, 1 gallon of water, and a few drops of liquid soap; apply every 7-10 days;Use neem oil as a foliar spray following package instructions;Try a milk solution (1 part milk to 9 parts water) as a preventive measure;Copper-based fungicides like Bordeaux mixture can reduce severity;Crush garlic cloves, steep in water, strain, dilute, and spray on plants;Apply organic mulch to prevent soil splash onto leaves;In severe cases, consider commercial fungicides.'),
    ('LB002','Late Blight','Late blight, caused by Phytophthora infestans, often affects potassium (K) in potatoes. High humidity and prolonged leaf wetness favor the pathogen. Overhead irrigation, rain, or high humidity promote its spread. Late blight is more common in slightly acidic to neutral pH soils (pH 5.0 to 7.0). Acidic soils inhibit pathogen growth, while alkaline soils affect nutrient uptake and disease resistance.','Use potato tubers for seed from disease-free areas to ensure that the pathogen is not carried through seed tuber; Destroy infected plant material;Opt for resistant varieties like Kufri Navtal; Apply fungicidal sprays at the first sign of symptoms (Dithane M-45 or Dithane Z-78,following pacakage instructions, with 10-12 day intervals);Practice crop rotation;Ensure proper irrigation.','Potato','Commercial solutions: Shop Dithane M-45: https://shop.plantix.net/en/products/pesticides/6fbd836d-7aca-4cdd-acbe-3a3c21449fc1/dithane-m-45-dow-/?srsltid=AfmBOoq2xJHHDq3h0KvtsSkZ_mokNhEnETtdhBWRrwS6MGJAmq8jGDxFnzU, https://kisancenter.in/product/23167028/Tata-M45-Fungicide--Mancozeb-75--WP-?vid=996850 ; Shop Dithane Z-78: https://agrosiaa.com/products/detail/indofil-z-78-contact-fungicide-250gm?gclid=CjwKCAjwloynBhBbEiwAGY25dBwI0dF0Ky55MQJ3h09qZKm3U4jf_LIW8N-RmTA6A-ZPByrA-Sq9KhoCba0QAvD_BwE; Home remedies: Home remedies are generally more effective as preventive measures or for early intervention; Copper-based fungicides like Bordeaux mixture can slow its spread;Remove and destroy infected leaves and stems promptly;Use a baking soda solution (1 tbsp baking soda, 1 gallon of water, a few drops of liquid soap) every 7-10 days for prevention;Try neem oil as a foliar spray following package instructions;Use a milk solution (1 part milk to 9 parts water) as a preventive measure;Crush garlic cloves, steep in water, strain, dilute, and spray;Note that home remedies may not completely cure late blight.For extensive late blight, consider commercial fungicides.')
]

c.executemany('INSERT INTO diseases (disease_code,disease_name,reason,measures,crop,suggestions) VALUES (?,?,?,?,?,?)', diseases_data)
conn.commit()
conn.close()